WebUI.MVC/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebUI.MVC.Models;
using WebUI.MVC.Services.Interfaces;

namespace WebUI.MVC.Controllers
{
    public class BookingsController : Controller
    {
        private readonly IBookingService _service;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public readonly IUserManagement _userManagement;


        public BookingsController(IBookingService service, IHttpContextAccessor httpContextAccessor, IUserManagement userManagement)
        {
            _service = service;
            _httpContextAccessor = httpContextAccessor;
            _userManagement = userManagement;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> All()
        {
            var bookings = await _service.GetAllAsync(await HttpContext.GetTokenAsync("access_token"));

            var idUser = "";
            if (User.Identity.IsAuthenticated)
            {
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                DateTime accessTokenExpiresAt = DateTime.Parse(
                    await HttpContext.GetTokenAsync("expires_at"),
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.RoundtripKind
                    );

                string idtoken = await HttpContext.GetTokenAsync("id_token");
                idUser = _httpContextAccessor.HttpContext.User.Claims.First(i => i.Type == ClaimTypes.NameIdentifier).Value;

                var userRoles = await _userManagement.GetUserRoles(idUser);
                var str = userRoles[0].Name;
                TempData["Role"] = str;
                TempData["UserName"] = _httpContextAccessor.HttpContext.User.Claims.ElementAt(0).Value;
            }

            return View(bookings);
        }


        public async Task<IActionResult> Create()
        {
            var idUser = "";
            if (User.Identity.IsAuthenticated)
            {
                string accessToken = await HttpContext.GetTokenAsync("access_token");
                DateTime accessTokenExpiresAt = DateTime.Parse(
                    await HttpContext.GetTokenAsync("expires_at"),
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.RoundtripKind
                    );

                string idtoken = await HttpContext.GetTokenAsync("id_token");
                idUser = _httpContextAccessor.HttpContext.User.Claims.First(i => i.Type == ClaimTypes.NameIdentifier).Value;

                var userRoles = await _userManagement.GetUserRoles(idUser);
                var str = userRoles[0].Name;
                TempData["Role"] = str;
                TempData["UserName"] = _httpContextAccessor.HttpContext.User.Claims.ElementAt(0).Value;
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Booking booking)
        {

            await _service.CreateAsync(booking, await HttpContext.GetTokenAsync("access_token"));
            TempData["Message"] = "Success : Booking has been created";
            return RedirectToAction("All");
        }

        public async Task<IActionResult> Details(int? id)
        {
            var booking = await _service.BookingDetailsAsync(id);
            return View(booking);
        }

      
        
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
                return NotFound();
            var booking = await _service.BookingDetailsAsync(id);
            if (booking == null)
                return NotFound();
            return View(booking);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Booking booking)
        {
            await _service.UpdateBookingAsync(id, booking);
            TempData["Message"] = "Success : Booking has been updated";
            return RedirectToAction("All");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                NotFound();
            }
            var booking = await _service.BookingDetailsAsync(id);
            return View(booking);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            await _service.DeleteBookingAsync(id);
            TempData["Message"] = "Warning : Booking has been deleted";
            return RedirectToAction("All");
        }



    }
}

WebUI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rent A Car </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/toastr.js/toastr.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css">
</head>

<span id="Toastr" class="d-none">@TempData["Message"]</span>

<body>
    <header>
        @{
            string style = "";
            string role = (string)@TempData["Role"];
            switch (role)
            {
                case "User":
                case "Agent":
                    style = "background-color:#3bbfff";
                    break;
                case "Admin":
                case "Owner":
                    style = "background-color:#3bff7b";
                    break;
                default:
                    style = "background-color:#ff7d3b";
                    break;
            }
        }

        <nav class="navbar navbar-expand-lg navbar-light" style="@style">
            <a class="navbar-brand" href="#">
                <img src="https://courmelles-handball.com/wp-content/uploads/2.png" alt="..." height="56">
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (User.Identity.IsAuthenticated)
            {
                <a class="navbar nav-link"><i class="fa-solid fa-user m-2"></i>Welcome @TempData["UserName"] | You're logged as <strong> : @TempData["Role"]</strong></a>
            }
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto topnav">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Booking Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if (!(((string)@TempData["Role"] == "User")))
                                {
                                    <a class="dropdown-item" asp-controller="Bookings" asp-action="Create">Create Booking</a>
                                }
                                <a class="dropdown-item" asp-controller="Bookings" asp-action="All">All Bookings</a>

                            </div>
                        </li>

                                    @if (!(((string)@TempData["Role"] == "User") || ((string)@TempData["Role"] == "Agent")))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    @if (((string)@TempData["Role"] == "Owner"))
                                    {
                                        <a class="dropdown-item" asp-controller="User" asp-action="CreateUser">Create User</a>
                                    }
                                    <a class="dropdown-item" asp-controller="User" asp-action="GetAll">All users</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Claims">Claims</a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <button type="button" class="nav-link btn btn-primary me-3" onclick="location.href='@Url.Action("Logout", "Home")'">LogOut</button>
                        </li>
                    }
                    else
                    {
                        <button type="button" class="btn btn-primary me-3" onclick="location.href='@Url.Action("Login", "Home")'">LogIn</button>
                    }
                </ul>
                </ul>
            </div>
            </div>
            </div>


        </nav>

        </nav>
        @if (!User.Identity.IsAuthenticated)
        {
            <div id="carouselExampleIndicators" class="carousel carousel-dark slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-inline-block w-100 h-100" src="~/Images/1.jpg" alt="First slide">
                        <div class="carousel-caption d-none d-md-block" style="color:yellow; font-size:40px">
                            <p><strong>Car rental service with smiling prices.</strong></p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-inline-block w-100 h-100" src="~/Images/2.jpg" alt="Second slide">
                        <div class="carousel-caption d-none d-md-block" style="color:greenyellow; font-size:40px">
                            <p><strong>Your friends to make your tour easy.</strong></p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img class="d-inline-block w-100 h-100" src="~/Images/3.jpg" alt="Third slide">
                        <div class="carousel-caption d-none d-md-block" style="color:black; font-size:40px">
                            <p><strong>Spend less and hire the best.</strong></p>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        }

    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="container text-center">
            <span class="text"><strong>© 2022 EPHEC - HAJI Mohamad - MONTILLA Francisco</strong></span>
        </div>
    </footer>
    <script src="~/lib/toastr.js/toastr.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/toast.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function(){
            $('.carousel').carousel();
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>